plugins:
  - jekyll-asciidoc

asciidoc:
  attributes:
    toc: true
    toc-title: "Table of Contents"
    numbered: true
plugins:
  - jekyll-asciidoc

asciidoc:
  attributes:
    toc: true
    toc-title: "Table of Contents"
    numbered: true
