name: Deploy

on:
  push:
    branches:
      - main

jobs:
  worker:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Use Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      - run: npm ci
      - run: npm run build
      - run: npx semantic-release
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}

  sitemaps:
    runs-on: ubuntu-latest
    needs: worker
    permissions:
      contents: write
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    steps:
      - uses: actions/checkout@v3
        with:
          ref: main
      - uses: actions/setup-node@v3
        with:
          node-version: '18'
      - run: npm ci
      - name: generate sitemaps
        run: ORIGIN='https://docs.prismacloud.io' npm run gen:sitemaps
      - name: push sitemaps
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: 'chore(sitemap): publish sitemaps [skip ci]'
          branch: main
          file_pattern: 'docs/sitemaps/*.xml'
          commit_user_name: 'github-actions[bot]'
          commit_options: '--no-verify'
          # push_options: '--force'
          disable_globbing: true
      - name: check sitemap-index
        run: ORIGIN='https://docs.prismacloud.io' node bin/check-sitemap-index.js