name: Docs

on:
  push:
    branches:
      - main

jobs:
  publish:
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Use Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      - run: npm ci
      - name: Get changed files
        run: |
          ARG_FILE="${{ runner.temp }}/to_publish"
          git diff --name-only --diff-filter=ACMRT ${{ github.event.before }} ${{ github.event.after }} | xargs > "$ARG_FILE"
      - run: node ./bin/batch-publish.js -f ${{ runner.temp }}/to_publish